apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-living-burro
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "323612486440"
    project: jenkins-x-314913
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: jenkins-x-pipeline-bot
    repository: jenkins-x-cluster
  - key: staging
  - key: production
  ingress:
    domain: 34.71.77.19.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: jenkins-x-pipeline-bot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-living-burro-d5fb84a283b7
  - name: reports
    url: gs://reports-tf-jx-living-burro-d5fb84a283b7
  - name: repository
    url: gs://repository-tf-jx-living-burro-d5fb84a283b7
  vault: {}
  webhook: lighthouse
