apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jenkins-x-pipeline-bot/jenkins-x-cluster: true
        jenkins-x-pipeline-bot/jx3-golang-demo: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jenkins-x-pipeline-bot/jenkins-x-cluster: merge
        jenkins-x-pipeline-bot/jx3-golang-demo: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-x-pipeline-bot/jenkins-x-cluster
        - jenkins-x-pipeline-bot/jx3-golang-demo
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-x-pipeline-bot/jenkins-x-cluster
        - jenkins-x-pipeline-bot/jx3-golang-demo
      target_url: http://dashboard-jx.34.71.77.19.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
